import { useMemo, useState } from 'react';
import { ArrowRight, CalendarClock, CheckCircle2, CircleDot, Clock3, Filter, MoveRight, UserRound, Video, Wand2 } from 'lucide-react';

const stages = ['Script Approved', 'Shoot Pending', 'Raw Footage Received', 'Video Editing', 'Internal QA', 'Client Review', 'Revision', 'Final Approved', 'Delivered'];
const queueTabs = ['All', 'Overdue', 'Due Today', 'Due Tomorrow', 'Completed'];
const initialVideos = [
  { id: 'VO-208', title: 'Serum texture / 3 ways', client: 'Nykaa Beauty', creator: 'Mira S.', editor: 'Karan D.', deadline: '18 Sep', day: 'today', stage: 3, revisions: 1, accent: 'bg-[#d9a441]' },
  { id: 'VO-207', title: 'Founder story / take 02', client: 'Northstar Labs', creator: 'Rohan K.', editor: 'Nikhil S.', deadline: '19 Sep', day: 'tomorrow', stage: 5, revisions: 0, accent: 'bg-[#6685a1]' },
  { id: 'VO-206', title: 'Festive unboxing hook', client: 'The Loom Room', creator: 'Ananya P.', editor: 'Karan D.', deadline: '17 Sep', day: 'overdue', stage: 6, revisions: 2, accent: 'bg-[#9b6d64]' },
  { id: 'VO-205', title: 'Night cream testimonial', client: 'Nykaa Beauty', creator: 'Mira S.', editor: 'Nikhil S.', deadline: '18 Sep', day: 'today', stage: 4, revisions: 0, accent: 'bg-[#d9a441]' },
  { id: 'VO-204', title: 'Summer linen / edit 03', client: 'The Loom Room', creator: 'Ananya P.', editor: 'Karan D.', deadline: '14 Sep', day: 'completed', stage: 8, revisions: 1, accent: 'bg-[#9b6d64]' },
  { id: 'VO-203', title: 'Productivity myth-buster', client: 'Northstar Labs', creator: 'Rohan K.', editor: 'Nikhil S.', deadline: '20 Sep', day: 'upcoming', stage: 1, revisions: 0, accent: 'bg-[#6685a1]' }
];

const filterMap = { 'Overdue': 'overdue', 'Due Today': 'today', 'Due Tomorrow': 'tomorrow', Completed: 'completed' };
function StageHeader({ stage, count }) { return <div className="sticky left-0 top-0 z-10 flex min-h-18 flex-col justify-between border-b border-line bg-[#151515] px-3 py-3"><div className="flex items-start justify-between gap-2"><span className="font-mono text-[9px] text-amber">0{stage + 1}</span><span className="grid h-5 min-w-5 place-items-center bg-[#292929] px-1 font-mono text-[9px] text-muted">{count}</span></div><p className="mt-2 text-[11px] font-medium leading-4 text-white">{stages[stage]}</p></div>; }

function VideoCard({ video, onAdvance }) {
  const isDone = video.stage === stages.length - 1;
  return <article className="group border border-line bg-panel p-3 transition hover:border-[#5a4215] hover:bg-panel-strong"><div className="flex items-start justify-between gap-2"><span className="font-mono text-[9px] text-amber">{video.id}</span><span className={`font-mono text-[9px] ${video.day === 'overdue' ? 'text-red-300' : video.day === 'completed' ? 'text-emerald-300' : 'text-muted'}`}>{video.day === 'overdue' ? 'OVERDUE' : video.day === 'completed' ? 'DONE' : video.deadline}</span></div><div className="mt-3 flex aspect-[1.75/1] items-end bg-[#252525] p-3"><span className={`grid h-8 w-8 place-items-center ${video.accent} text-ink`}><Video size={15} /></span><span className="ml-auto font-mono text-[9px] text-[#777]">16:9</span></div><h3 className="mt-3 text-xs font-semibold leading-4 text-white">{video.title}</h3><p className="mt-1 truncate text-[10px] text-muted">{video.client}</p><div className="mt-4 space-y-2 border-t border-line pt-3"><p className="flex items-center gap-2 text-[10px] text-muted"><UserRound size={12} className="text-[#666]" /> {video.creator} <span className="ml-auto text-[#555]">creator</span></p><p className="flex items-center gap-2 text-[10px] text-muted"><Wand2 size={12} className="text-[#666]" /> {video.editor} <span className="ml-auto text-[#555]">editor</span></p><div className="flex items-center justify-between pt-1"><span className="flex items-center gap-1 font-mono text-[9px] text-orange-300"><CircleDot size={11} /> {video.revisions} revision{video.revisions === 1 ? '' : 's'}</span>{!isDone && <button onClick={() => onAdvance(video.id)} title={`Move to ${stages[video.stage + 1]}`} className="flex items-center gap-1 text-[9px] font-bold uppercase tracking-[0.08em] text-amber opacity-70 transition hover:opacity-100 group-hover:opacity-100">Advance <MoveRight size={12} /></button>}{isDone && <CheckCircle2 size={14} className="text-emerald-400" />}</div></div></article>;
}

export default function VideoPipeline() {
  const [videos, setVideos] = useState(initialVideos);
  const [queue, setQueue] = useState('All');
  const filtered = useMemo(() => videos.filter((video) => queue === 'All' || video.day === filterMap[queue]), [videos, queue]);
  const advanceVideo = (id) => setVideos((current) => current.map((video) => video.id === id && video.stage < stages.length - 1 ? { ...video, stage: video.stage + 1, day: video.stage + 1 === stages.length - 1 ? 'completed' : video.day } : video));
  return <div className="animate-rise-in space-y-7"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="page-kicker">Workspace / Production control</p><h1 className="page-title">Video pipeline<span className="text-amber">.</span></h1><p className="page-subtitle">Move every asset forward, one controlled state at a time.</p></div><div className="flex items-center gap-2 border border-line bg-panel px-3 py-2"><span className="h-2 w-2 bg-amber pulse-amber" /><span className="font-mono text-[10px] uppercase tracking-[0.12em] text-muted">{videos.length} live assets</span></div></div><div className="flex flex-col justify-between gap-4 border-y border-line py-4 lg:flex-row lg:items-center"><div className="scrollbar-thin flex gap-1 overflow-x-auto">{queueTabs.map((tab) => <button key={tab} onClick={() => setQueue(tab)} className={`whitespace-nowrap px-3 py-2 font-mono text-[10px] uppercase tracking-widest ${queue === tab ? 'bg-amber text-ink' : 'text-muted hover:bg-panel hover:text-white'}`}>{tab}</button>)}</div><div className="flex items-center gap-4 font-mono text-[10px] uppercase tracking-[0.12em] text-muted"><span className="flex items-center gap-2"><CalendarClock size={13} className="text-amber" /> {filtered.length} visible</span><span className="hidden items-center gap-2 sm:flex"><Filter size={13} /> Editor queue</span></div></div><div className="overflow-x-auto border border-line bg-[#141414] pb-3"><div className="grid min-w-385 grid-cols-9 gap-px bg-line">{stages.map((stage, index) => <section key={stage} className="min-w-0 bg-[#141414]"><StageHeader stage={index} count={filtered.filter((video) => video.stage === index).length} /><div className="space-y-2 p-2">{filtered.filter((video) => video.stage === index).map((video) => <VideoCard key={video.id} video={video} onAdvance={advanceVideo} />)}{!filtered.some((video) => video.stage === index) && <div className="flex min-h-32 items-center justify-center border border-dashed border-[#2b2b2b] font-mono text-[9px] uppercase tracking-[0.12em] text-[#555]">Empty lane</div>}</div></section>)}</div></div><div className="flex flex-col justify-between gap-3 border border-line bg-panel p-4 text-xs text-muted sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center bg-[#2b2110] text-amber"><Clock3 size={14} /></span><span><b className="font-medium text-white">Linear flow is active.</b> Assets can only advance to the next production state.</span></div><span className="flex items-center gap-1 font-mono text-[9px] uppercase tracking-widest text-amber">{stages.length} controlled states <ArrowRight size={12} /></span></div></div>;
}
